In [1]:
import numpy as np
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [2]:
python_list = [[1, 2, 3], [4, 5, 6], [7, 8, 8]]
np_list = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])

In [3]:
print(python_list)
print(np_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 8]]
[[1 2 3]
 [4 5 6]
 [7 8 8]]


In [4]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [8]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
array1 % array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [11]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [12]:
array1 - array2

array([[ 0,  0,  0],
       [-3, -3, -3],
       [-6, -6, -6]])

In [13]:
array1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [22]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

In [23]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]])

In [24]:
array1.shape

(3,)

In [25]:
array2.shape

(4, 3)

In [27]:
array2[2, 2]

9

In [28]:
array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [29]:
array3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [30]:
array3[2]

array([[ 9, 10],
       [11, 12]])

In [32]:
array3[2, 1]

array([11, 12])

In [33]:
array3[2, 1, 1]

12

In [34]:
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
array2[:, :1]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [37]:
array2[:3, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
array2[1:, :2]

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [39]:
array2[1:3, 1:]

array([[5, 6],
       [8, 9]])